apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "nekocafe.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env | quote }}
  APP_VERSION: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  OTEL_SERVICE_NAME: {{ .Release.Name | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otlpEndpoint | quote }}
  OTEL_TRACES_SAMPLER_ARG: {{ .Values.config.traceSampleRatio | quote }}
  {{- with .Values.config.memberServiceUrl }}
  MEMBER_SERVICE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.redisUrl }}
  REDIS_URL: {{ . | quote }}
  {{- end }}
